add rspecs for controllers and models
SerhiiBorozenets/react-project pull request #20
Opened 2022-12-06 13:34 UTC by SerhiiBorozenets

https://github.com/SerhiiBorozenets/react-project/issues/1

2022-12-06 17:07 UTC, rogergraves requested changes
Nice work for a first try on this 👍🏻

2022-12-06 17:07 UTC, rogergraves commented on spec/models/user_spec.rb
> +      expect(user.valid?).to be_falsey
Also can use `expect(user).to_not be_valid`

2022-12-07 17:23 UTC, SerhiiBorozenets commented on spec/controllers/api/v1/projects_controller_spec.rb
> +      project_saved = Project.find_by(title: project[:title])
@rogergraves unfortunately `project` from line 6 has only params `{ attributes_for :project, user_id: user.id }` , so I should find `saved project` in db and check fields.

2022-12-07 17:24 UTC, SerhiiBorozenets commented on spec/controllers/api/v1/projects_controller_spec.rb
> +      project = Project.create(title: Faker::Hobby.activity, user_id: user.id)
thanks

2022-12-07 17:24 UTC, SerhiiBorozenets commented on app/models/user.rb
> +  validates :password, presence: true, length: { minimum: 6, maximum: 128 }
thanks

2022-12-07 17:29 UTC, SerhiiBorozenets commented on spec/controllers/api/v1/projects_controller_spec.rb
> +  let!(:project) { attributes_for :project, user_id: user.id }
@rogergraves I used it like params for creating project, so I renamed it to `let!(:project_attr) { attributes_for :project, user_id: user.id }`. Thanks

2022-12-07 17:31 UTC, SerhiiBorozenets commented on spec/controllers/api/v1/projects_controller_spec.rb
> +      project = Project.create(title: Faker::Hobby.activity, user_id: user.id)
thanks

2022-12-07 17:34 UTC, SerhiiBorozenets commented on spec/factories.rb
> +  end
thanks

2022-12-07 17:35 UTC, SerhiiBorozenets commented on spec/factories.rb
> +    completed { Faker::Boolean.boolean }
thanks

2022-12-07 17:38 UTC, SerhiiBorozenets commented on spec/models/project_spec.rb
> +  let!(:user) { create :user }
thanks

2022-12-07 17:57 UTC, SerhiiBorozenets commented on spec/models/project_spec.rb
> +      project_2 = Project.create(title: "The project", user_id: user.id)
thanks

2022-12-07 17:58 UTC, SerhiiBorozenets commented on spec/models/project_spec.rb
> +      project = Project.create(title: Faker::Hobby.activity, user_id: user.id)
thanks

2022-12-07 18:16 UTC, SerhiiBorozenets commented
@rogergraves please take a look when you have time https://github.com/SerhiiBorozenets/react-project/pull/20/commits/e8831cf39a4e0771cd8b880c3deaf0d80322b326

2022-12-07 18:33 UTC, rogergraves approved these changes
Nice work! 👍🏻

2022-12-07 18:38 UTC, merged